
; Removes little annoyances
(setq visual-basic-capitalize-keywords-p nil)
(setq visual-basic-mode-indent 4)

; Uses parfait to lessen the burden of ugliness in the eyes
(defun parfait-visual-basic ()
  (interactive)
  (make-local-variable 'parfait-stable)
  (setq parfait-symtable '())
  (setq tab-width 80)
  (parfait-add-symbols
   '(("\\<function\\>"        . "𝝺")
     ("\\<return\\>"          . "<-")
     ("\\>_\\<"               . "-")
     ("<="                    . "≤")
     (">="                    . "≥")
     ("\\<and\\>"             . "∧")
     ("\\<or\\>"              . "∨")
     ("<>"                    . "≠")
     (" & "                   . " . ")
     ("\\<byval "             . "º")
     ("\\<call "              . "›")
     ("\\<set "               . "*")
     ("\\<case\\>"            . "—")
     ("\\<elseif\\>"          . "else if")
     ("\\<forall\\>"          . "∀")
     ("\\<me\\(\\.\\|\\>\\)"  . "@")
     ("\\<not\\>"             . "¬")
     ("\\<%?rem\\>"           . "『")
     ("\\<%end rem\\>"        . "』")
     (" then\\>"              . ":")
     ("\\<as[ 	]+"           . ": ")
     ("[ 	 ]+=[ 	]+"       . " = ")
     ("\\<wend\\>"            . "/while")
     ("\\<xor\\>"             . "⊻")
     ("\\<loop\\>"            . "↺")
     ("[ 	]_[ 	]*$"      . "	↲")))
  (parfait-mode t))

(add-hook 'vbscript-mode-hook 'parfait-visual-basic)
(add-hook 'vbscript-mode-hook
          '(lambda()
             (local-set-key (kbd "<RET>") 'newline)))
